name: Setup Node and install dependencies
description: Setup Node.js with npm cache and install project dependencies.

inputs:
  node-version:
    description: Node.js version to use.
    required: false
    default: "20"

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm ci --include=optional
